### ISSUE TITLE
No database or notification directories

### ISSUE THREAD

**Issue by jsonify** [poeticninja/hapi-ninja#19]
Your repo looks great. Unfortunately, I'm not able to start the server due to the following message:

Error: Cannot find module './server/database/index.js'

And upon looking at the 'server.js' file, it appears that the file is also requesting the 'index.js' file from the 'notifications' folder, of which also does not appear to exist in your 'hapi-ninja' folder structure. Any suggestions?

**Comment by poeticninja** [comment]
Sorry, I accidentally left in a couple lines when I was making updates. This is fixed as of this commit a9719ae95266f486fccb150b22da00b3429eeb87.

Just pull the most recent. Thanks! :smile:
